### ISSUE TITLE
Runtime dependencies not declared in mix.exs

### ISSUE THREAD

**Issue by bradleygolden** [c-rack/plug_cloudflare#15]
This application's dependencies must be specified in `applications` or `extra_applications` because they are not declared as runtime dependencies in `mix.exs`. This isn't ideal because it doesn't take advantage of elixir's way to automatically infer runtime dependencies and it means we have to manually include them.

Note the dependencies here:

https://github.com/c-rack/plug_cloudflare/blob/731abed58b3bbff1580bc5ff0c9b6db845b68b35/mix.exs#L9-L11

Note the application block here:

https://github.com/c-rack/plug_cloudflare/blob/731abed58b3bbff1580bc5ff0c9b6db845b68b35/mix.exs#L37-L39

Notice that both `cidr` and `plug` are runtime dependencies but they are not declared in the application block.

I think one alternative to solve this issue is to either add them to the application block or remove `applications: []` altogether from the application block.

**Comment by c-rack** [comment]
@bradleygolden Thanks for openening this issue! Feel free to send a pull request and I will merge it as soon as possible.

**Comment by bradleygolden** [comment]
Thank you for your fast response. I'll submit a PR today!

**Comment by mtarnovan** [comment]
Sorry for the necromancy, but could a new hex version be released that includes this fix? I was really confused by this, especially since I looked at `mix.exs` (but on master...) and saw `cidr` was included in `applications`.
